name: Build MOOS-IvP Extend repository
on: [push]

jobs:

  build-extend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'moos-ivp-extend'
      - run: git clone https://github.com/moos-ivp/moos-ivp.git
      - name: Build MOOS-IvP
        working-directory: moos-ivp
        run: |
          ./build-moos.sh --minrobot --release
          ./build-ivp.sh --nogui
      - name: Build moos-ivp-extend
        working-directory: moos-ivp-extend
        run: |
          ./build.sh
